// Generated by CoffeeScript 1.12.7
(function() {
  var AutoSuggest;

  window.AutoSuggest = AutoSuggest = (function() {
    function AutoSuggest() {
      this.displayDetails;
    }

    AutoSuggest.prototype.init = function() {
      this.options = {
        url: "./json/countries.json",
        getValue: "country_name",
        list: {
          match: {
            enabled: true
          },
          onChooseEvent: function() {
            var countryname, dialingcode;
            countryname = $("#searchInput").getSelectedItemData().country_name;
            dialingcode = $("#searchInput").getSelectedItemData().dialling_code;
            console.log(countryname + " , " + dialingcode);
            this.displayDetails = '<li class="attribute" ><strong>Country Name: </strong>' + countryname + '</li><li class="value"><strong>Dialling Code: </strong>' + dialingcode + '</li>';
            return $(".Results_list").html(this.displayDetails);
          }
        }
      };
      $("#searchInput").easyAutocomplete(this.options);
      this.widthOnPageLoad();
      return $(".Search_Button").on('click', (function(_this) {
        return function() {
          return _this.onSearchClick();
        };
      })(this));
    };

    AutoSuggest.prototype.widthOnPageLoad = function() {
      $(".easy-autocomplete").css("width", "100%");
      return $("#searchInput").css("width", "100%");
    };

    AutoSuggest.prototype.onSearchClick = function() {
      var inputbox, parentwidth, searchValue;
      searchValue = $("#searchInput").val();
      console.log(searchValue.length);
      parentwidth = $(".easy-autocomplete").width();
      console.log(parentwidth);
      this.options.list.onChooseEvent();
      inputbox = '<input class="Search_Input" value ="' + searchValue + '" type ="text" />';
      $("#searchInput").val(" ");
      return $(".easy-autocomplete").prepend(inputbox);
    };

    return AutoSuggest;

  })();

  $(document).ready(function() {
    var autoObject;
    autoObject = new AutoSuggest();
    return autoObject.init();
  });

}).call(this);
