// Generated by CoffeeScript 1.12.7
(function() {
  var AutoSuggest;

  window.AutoSuggest = AutoSuggest = (function() {
    function AutoSuggest() {
      this.displayDetails;
      this.boxWidth = 0;
      this.countryNames = [];
      this.currentUrl = window.location.hrefs;
      this.countryObject = {};
      this.i = 1;
    }

    AutoSuggest.prototype.init = function() {
      this.options = {
        url: "./json/countries.json",
        getValue: "country_name",
        list: {
          match: {
            enabled: true
          },
          onChooseEvent: function() {
            var countryname, dialingcode;
            countryname = $("#searchInput").getSelectedItemData().country_name;
            dialingcode = $("#searchInput").getSelectedItemData().dialling_code;
            console.log(countryname + " , " + dialingcode);
            this.displayDetails = '<li class="attribute" ><strong>Country Name: </strong>' + countryname + '</li><li class="value"><strong>Dialling Code: </strong>' + dialingcode + '</li>';
            return $(".Results_list").append(this.displayDetails);
          },
          onClickEvent: (function(_this) {
            return function() {
              return _this.createBoxDynamically();
            };
          })(this)
        }
      };
      $("#searchInput").easyAutocomplete(this.options);
      this.widthOnPageLoad("page  url" + this.currentUrl);
      $(".Search_Button").on('click', (function(_this) {
        return function() {
          return _this.onSearchClick();
        };
      })(this));
      return $("#searchInput").on('keydown', (function(_this) {
        return function(e) {
          var keyCode;
          keyCode = e.keyCode || e.which;
          if (keyCode === 9) {
            e.preventDefault();
            return _this.createBoxDynamically();
          }
        };
      })(this));
    };

    AutoSuggest.prototype.widthOnPageLoad = function() {
      $(".easy-autocomplete").css("width", "100%");
      return $("#searchInput").css("width", "100%");
    };

    AutoSuggest.prototype.createBoxDynamically = function() {
      var dynamicWidth, inputbox, latestname, parentwidth, searchValue, spanElement;
      parentwidth = $(".easy-autocomplete").width();
      searchValue = $("#searchInput").val();
      if (searchValue.length > 25) {
        dynamicWidth = searchValue.length * 8;
      } else {
        dynamicWidth = searchValue.length * 7;
      }
      inputbox = '<input class="Search_Input dynamicInput" " type ="text" value ="' + searchValue + '" style="width:' + dynamicWidth + 'px" />';
      spanElement = '<span class = "Search_Span" >' + inputbox + '</span>';
      $("#searchInput").val(" ");
      $(".easy-autocomplete").prepend(spanElement);
      latestname = $(".dynamicInput:first").val();
      this.countryObject['name' + this.i] = latestname;
      this.i += 1;
      console.log(this.countryObject);
      return this.changeMainSearchWidth(dynamicWidth + 16);
    };

    AutoSuggest.prototype.changeMainSearchWidth = function(dynamicWidth) {
      this.boxWidth += dynamicWidth;
      if (this.boxWidth > 440) {
        $("#searchInput").css("width", "461px");
        return this.dynamicWidth = 0;
      } else {
        return $("#searchInput").css("width", "calc(100% - " + this.boxWidth + "px)");
      }
    };

    AutoSuggest.prototype.onSearchClick = function() {
      var advancedUrl, recursiveDecoded;
      recursiveDecoded = decodeURIComponent($.param(this.countryObject));
      console.log("search terms :- " + recursiveDecoded);
      advancedUrl = this.currentUrl + "?" + recursiveDecoded;
      console.log("final url:- " + advancedUrl);
      return window.location.href = advancedUrl;
    };

    return AutoSuggest;

  })();

  $(document).ready(function() {
    var autoObject;
    autoObject = new AutoSuggest();
    return autoObject.init();
  });

}).call(this);
