// Generated by CoffeeScript 1.12.7
(function() {
  var AutoSuggest;

  window.AutoSuggest = AutoSuggest = (function() {
    function AutoSuggest() {
      this.displayDetails;
      this.boxWidth = 0;
      this.countryNames = [];
      this.currentUrl = window.location.href;
      this.countryObject = {};
      this.encodedSearchTerm;
      this.i = 1;
    }

    AutoSuggest.prototype.init = function() {
      this.options = {
        url: "./json/countries.json",
        getValue: "country_name",
        list: {
          match: {
            enabled: true
          },
          onChooseEvent: function() {
            var countryname, dialingcode;
            countryname = $("#searchInput").getSelectedItemData().country_name;
            dialingcode = $("#searchInput").getSelectedItemData().dialling_code;
            console.log(countryname + " , " + dialingcode);
            this.displayDetails = '<li class="name"><p><label><strong>Country Name: </strong></label><label class = "countryname" >' + countryname + '</label></p><p class="code"><label><strong>Dialling Code: </strong></label><label class = "dialingcode" >' + dialingcode + '</label></p></li>';
            return $(".Results_list").append(this.displayDetails);
          },
          onClickEvent: (function(_this) {
            return function() {
              return _this.createBoxDynamically();
            };
          })(this)
        }
      };
      $("#searchInput").easyAutocomplete(this.options);
      console.log(window.location.href);
      this.widthOnPageLoad();
      $(".Search_Button").on('click', (function(_this) {
        return function() {
          var advancedUrl, inputBoxes, modifiedValue, newurl;
          modifiedValue = "";
          inputBoxes = $(".Search_InputWrapper").find(".DynamicInput");
          $.each(inputBoxes, function(index, elements) {
            var searchValue;
            searchValue = $(elements).val();
            return modifiedValue = modifiedValue + searchValue + "+";
          });
          modifiedValue = modifiedValue.substring(0, modifiedValue.length - 1);
          advancedUrl = _this.currentUrl + "?countryNames=" + modifiedValue;
          console.log(advancedUrl);
          if (history.pushState) {
            newurl = advancedUrl;
            return window.history.pushState({
              path: newurl
            }, '', newurl);
          }
        };
      })(this));
      $("#searchInput").on('keydown', (function(_this) {
        return function(e) {
          var keyCode;
          keyCode = e.keyCode || e.which;
          if (keyCode === 9) {
            e.preventDefault();
            return _this.createBoxDynamically();
          }
        };
      })(this));
      return $(".Search_InputWrapper").on("click", ".Search_cross", (function(_this) {
        return function(e) {
          var closestEle, res, valueToBeRemoved;
          closestEle = $(e.currentTarget);
          valueToBeRemoved = closestEle.siblings("input").val();
          res = $(".Results_list").find("li .countryname");
          $.each(res, function(i, v) {
            if (valueToBeRemoved === $(v).html()) {
              return $(v).parent().parent().remove();
            }
          });
          return _this.removeItemFromInput(closestEle);
        };
      })(this));
    };

    AutoSuggest.prototype.widthOnPageLoad = function() {
      $(".easy-autocomplete").css("width", "100%");
      return $("#searchInput").css("width", "100%");
    };

    AutoSuggest.prototype.createBoxDynamically = function() {
      var dynamicWidth, inputbox, searchValue, spanElement;
      searchValue = $("#searchInput").val();
      dynamicWidth = searchValue.length * 8;
      if (searchValue.length > 24) {
        dynamicWidth = searchValue.length * 7;
      } else {
        dynamicWidth = searchValue.length * 8;
      }
      inputbox = '<input class="Search_Input DynamicInput" " type ="text" value ="' + searchValue + '"/>' + '<a class="Search_cross">×</a>';
      spanElement = '<span class = "SearchSpan" style="width:' + dynamicWidth + 'px" >' + inputbox + '</span>';
      $("#searchInput").val("");
      $(".easy-autocomplete").prepend(spanElement);
      return this.changeMainSearchWidth(dynamicWidth + 24);
    };

    AutoSuggest.prototype.changeMainSearchWidth = function(dynamicWidth) {
      this.boxWidth += dynamicWidth;
      if (this.boxWidth > 440) {
        $("#searchInput").css("width", "461px");
        return this.dynamicWidth = 0;
      } else {
        return $("#searchInput").css("width", "calc(100% - " + this.boxWidth + "px)");
      }
    };

    AutoSuggest.prototype.removeItemFromInput = function(current) {
      current.parent("span").next(".DynamicInput").remove();
      return current.parent("span").remove();
    };

    return AutoSuggest;

  })();

  $(document).ready(function() {
    var autoObject;
    autoObject = new AutoSuggest();
    return autoObject.init();
  });

}).call(this);
